from python:3.8-alpine
WORKDIR /code
ENV FLASK_APP main.py
ENV FLASK_RUN_HOW 0.0.0.0
RUN apk add --no-cash gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["flask","run"]